language: node_js
node_js:
- "4.0"
- "4.2.3"
- "5"
matrix:
  fast_finish: true
script: "npm run-script test-travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
sudo: false
